export const PHASE_12B_MAX_RECEIPT_FILE_BYTES = 4194304;
export const PHASE_12B_SERVER_ACTION_BODY_LIMIT_BYTES = 4350000;
export const PHASE_12B_MAX_DECODED_PIXELS = 20000000;
export const PHASE_12B_MAX_DIMENSION_PX = 8192;
export const PHASE_12B_NORMALIZED_MAX_LONG_EDGE_PX = 2048;
export const PHASE_12B_MAX_NORMALIZED_IMAGE_BYTES = 4194304;

export const PHASE_12B_MAX_PROVIDER_CALLS_PER_ANALYZE = 1;
export const PHASE_12B_PROVIDER_HTTP_ATTEMPTS = 1;
export const PHASE_12B_PROVIDER_AUTO_RETRY = false;

export const PHASE_12B_MAX_CATEGORY_CANDIDATES = 50;
export const PHASE_12B_MAX_CATEGORY_LABEL_LENGTH = 50;

export const RECEIPT_VISION_ERRORS = {
  RECEIPT_FILE_REQUIRED: 'RECEIPT_FILE_REQUIRED',
  RECEIPT_FILE_TOO_LARGE: 'RECEIPT_FILE_TOO_LARGE',
  RECEIPT_FILE_TYPE_UNSUPPORTED: 'RECEIPT_FILE_TYPE_UNSUPPORTED',
  RECEIPT_FILE_INVALID: 'RECEIPT_FILE_INVALID',
  RECEIPT_IMAGE_TOO_LARGE: 'RECEIPT_IMAGE_TOO_LARGE',
  RECEIPT_IMAGE_MULTIFRAME_UNSUPPORTED: 'RECEIPT_IMAGE_MULTIFRAME_UNSUPPORTED',
  RECEIPT_IMAGE_NORMALIZED_TOO_LARGE: 'RECEIPT_IMAGE_NORMALIZED_TOO_LARGE',
  RECEIPT_IMAGE_DECODE_FAILED: 'RECEIPT_IMAGE_DECODE_FAILED',
} as const;
